### ISSUE TITLE
Exception "Parameter count mismatch" while using TableEntity.Flatten

### ISSUE THREAD

**Issue by geekwhocodes** [Azure/azure-cosmos-table-dotnet#29]
### Exception "Parameter count mismatch"
I am trying to flatten complex object like List<T> and getting this exception. 
This is consistent, Am I doing something wrong here? 

**SDK Version** - Microsoft.Azure.Cosmos.Table 1.1.0.6 and NetCore 2.2
**Steps to reproduce :** 

```
        public class Root
        {
            public int Id { get; protected set; }
            public string DirName { get; protected set; }

            public List<Child> Childrens { get; protected set; }
            
            public Root() { }
            public Root(int id, string dirName, List<Child> childrens)
            {
                Id = id;
                DirName = dirName;
                Childrens = childrens;
            }
        }

        public class Child
        {
            public Child() { }
            public Child(string name)
            {
                Name = name;
            }
            public string Name { get; protected set; }
        }
```

```
Root root = new Root(1, "c", new List<Child>() { new Child("sys")});
Dictionary<string, EntityProperty> result = EntityPropertyConverter.Flatten(root, new OperationContext());
IDictionary<string, EntityProperty> result2 = TableEntity.Flatten(root, new OperationContext());

```
**Exception "Parameter count mismatch." at 
Dictionary<string, EntityProperty> result = EntityPropertyConverter.Flatten(root, new OperationContext());
Or 
IDictionary<string, EntityProperty> result2 = TableEntity.Flatten(root, new OperationContext());**

**This issue is consistent.**

**Stack Trace :** 

```
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Microsoft.Azure.Cosmos.Table.EntityPropertyConverter.<>c__DisplayClass5_0.<Flatten>b__1(PropertyInfo propertyInfo)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Azure.Cosmos.Table.EntityPropertyConverter.Flatten(Dictionary`2 propertyDictionary, Object current, String objectPath, HashSet`1 antecedents, EntityPropertyConverterOptions entityPropertyConverterOptions, OperationContext operationContext)
   at Microsoft.Azure.Cosmos.Table.EntityPropertyConverter.<>c__DisplayClass5_0.<Flatten>b__1(PropertyInfo propertyInfo)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Azure.Cosmos.Table.EntityPropertyConverter.Flatten(Dictionary`2 propertyDictionary, Object current, String objectPath, HashSet`1 antecedents, EntityPropertyConverterOptions entityPropertyConverterOptions, OperationContext operationContext)
   at Microsoft.Azure.Cosmos.Table.EntityPropertyConverter.Flatten(Object root, EntityPropertyConverterOptions entityPropertyConverterOptions, OperationContext operationContext)
```

**Comment by sakash279** [comment]
Hi, I agree with you that the error is misleading, which we should fix on our end in a subsequent release. 
However, your use case is not valid here. You are providing a property (List in your example) which is not supported in the Tables API supported property types : https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model#property-types

**Comment by geekwhocodes** [comment]
Thanks for the reply. I know that Table storage supports subset of data types defined in Odata specification but would it be possible to add an overload method to support other types which will convert those types to json with default Json converter? 

Example :
{"Id":1,"DirName":"c","Childrens":[{"Name":"sys"}]}

**Comment by ThomasWeiss** [comment]
@geekwhocodes Thanks for your inputs! Your feedback has been added to our backlog and will be considered for future releases. In the meantime, you may want to look at other libraries - like [this one](https://www.nuget.org/packages/ObjectFlattenerRecomposer/) - that address your requirement.

**Comment by geekwhocodes** [comment]
Happy to help! 
Gone through [ObjectFlattenerRecomposer](https://www.nuget.org/packages/ObjectFlattenerRecomposer/), code for this package is not available so I am bit worried about using it.

**Comment by geekwhocodes** [comment]
Happy to help!
Gone through [ObjectFlattenerRecomposer](https://www.nuget.org/packages/ObjectFlattenerRecomposer/). I have my own doubts because code for this package is not available.
